# Generated by Django 5.1.6 on 2025-02-28 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, unique=True)),
                ('short_name', models.CharField(default='', max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Genai_Institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('enrollments', models.IntegerField(default=0)),
                ('onboarded', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('pending', models.IntegerField(default=0)),
                ('revoked', models.IntegerField(default=0)),
                ('declined', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('beginner_completions', models.IntegerField(default=0)),
                ('intermediate_completions', models.IntegerField(default=0)),
                ('advanced_completions', models.IntegerField(default=0)),
                ('digital_badges', models.IntegerField(default=0)),
                ('completions_ratio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Genai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='student', max_length=15)),
                ('rollno', models.CharField(blank=True, max_length=21, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('consent', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('college', models.CharField(blank=True, max_length=225, null=True)),
                ('branch_other', models.CharField(blank=True, max_length=150, null=True)),
                ('year_of_joining', models.IntegerField(blank=True, null=True)),
                ('lateral_entry', models.BooleanField(default=False)),
                ('section', models.CharField(blank=True, max_length=4, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=21, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('designation_other', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.URLField(blank=True, max_length=225, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=24, null=True)),
                ('beginner_count', models.IntegerField(default=0)),
                ('beginner_badges', models.CharField(blank=True, max_length=225, null=True)),
                ('beginner_status', models.CharField(blank=True, max_length=3, null=True)),
                ('intermediate_count', models.IntegerField(default=0)),
                ('intermediate_badges', models.CharField(blank=True, max_length=300, null=True)),
                ('intermediate_status', models.CharField(blank=True, max_length=3, null=True)),
                ('advanced_count', models.IntegerField(default=0)),
                ('advanced_badges', models.CharField(blank=True, max_length=465, null=True)),
                ('advanced_status', models.CharField(blank=True, max_length=3, null=True)),
                ('enrollment_status', models.CharField(blank=True, max_length=15, null=True)),
                ('completion_status', models.CharField(blank=True, max_length=15, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('branch_code', models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, to='dashboard.branch')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('college', models.CharField(max_length=225)),
                ('role', models.ForeignKey(default=24, on_delete=django.db.models.deletion.PROTECT, to='dashboard.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
