# Generated by Django 5.1.6 on 2025-02-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90, unique=True)),
                ('short_name', models.CharField(default='', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90, unique=True)),
                ('type', models.CharField(choices=[('academic', 'academic'), ('corporate', 'corporate'), ('government', 'government')], default='academic', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90, unique=True)),
                ('type', models.CharField(choices=[('academic', 'academic'), ('corporate', 'corporate'), ('government', 'government')], default='academic', max_length=90)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('code', models.CharField(default='', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge_Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=60, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='O', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('aadhaar_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('short_name', models.CharField(default='', max_length=9)),
                ('degree_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.degree')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=30, null=True)),
                ('aicte_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('eamcet_code', models.CharField(blank=True, max_length=15, null=True)),
                ('l4g_code', models.CharField(default='', max_length=9, unique=True)),
                ('l4g_group_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('type', models.CharField(choices=[('Public University', 'Public University'), ('Private University-State', 'Private University-State'), ('Private University-Deemed to be', 'Private University-Deemed to be'), ('Autonomous College', 'Autonomous College'), ('Affiliated College', 'Affiliated College'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('latlong', models.CharField(blank=True, max_length=60, null=True)),
                ('district_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.district')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('info', models.TextField(blank=True, null=True)),
                ('knowledge_partner_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.knowledge_partner')),
            ],
        ),
        migrations.CreateModel(
            name='Learner_Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_joining', models.IntegerField(default=0)),
                ('year_of_graduation', models.IntegerField(default=0)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.branch')),
                ('institution_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.institution')),
                ('learner_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.learner')),
            ],
        ),
        migrations.CreateModel(
            name='Learner_Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(default='', max_length=30)),
                ('year_of_joining', models.IntegerField(default=0)),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department')),
                ('designation_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.designation')),
                ('institution_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.institution')),
                ('learner_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.learner')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('info', models.TextField(blank=True, null=True)),
                ('module_sequence_number', models.IntegerField(default=0)),
                ('theory_practical', models.CharField(choices=[('T', 'theory'), ('P', 'practical')], default='T', max_length=90)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('info', models.TextField(blank=True, max_length=255, null=True)),
                ('knowledge_partner_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.knowledge_partner')),
            ],
        ),
        migrations.CreateModel(
            name='Program_Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.program')),
            ],
        ),
        migrations.CreateModel(
            name='Learner_Program_Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('learner_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.learner')),
                ('program_requirement_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.program_requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('info', models.TextField(blank=True, max_length=255, null=True)),
                ('knowledge_partner_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.knowledge_partner')),
            ],
        ),
        migrations.CreateModel(
            name='Program_Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.program')),
                ('specialization_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.specialization')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='programs', through='main.Program_Specialization', to='main.specialization'),
        ),
        migrations.CreateModel(
            name='Specialization_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_sequence_number', models.IntegerField(default=0)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('specialization_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.specialization')),
            ],
        ),
        migrations.AddField(
            model_name='specialization',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='specializations', through='main.Specialization_Course', to='main.course'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('code', models.CharField(default='', max_length=15, unique=True)),
                ('country_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.country')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.state'),
        ),
    ]
