# Generated by Django 5.1.6 on 2025-04-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner_Course_Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('learner_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.learner')),
            ],
        ),
        migrations.CreateModel(
            name='Learner_Module_Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('learner_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.learner')),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.module')),
            ],
        ),
        migrations.CreateModel(
            name='Learner_Program_Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enrolled', models.BooleanField(default=False)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('duration_hrs', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('learner_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.learner')),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.program')),
            ],
        ),
        migrations.CreateModel(
            name='Learner_Specialization_Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('learner_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.learner')),
                ('specialization_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.specialization')),
            ],
        ),
    ]
