# Generated by Django 5.1.6 on 2025-04-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_learner_course_progress_learner_module_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('new_institution', models.CharField(default='', max_length=255)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=255)),
                ('datetime', models.DateTimeField()),
                ('event_url', models.URLField(unique=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.TextField(blank=True, max_length=500, null=True)),
                ('event_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('event_photo_url', models.URLField(blank=True, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.institution')),
                ('program_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.program')),
                ('trainers', models.ManyToManyField(related_name='events', to='main.learner_employment')),
            ],
        ),
    ]
