# Generated by Django 5.1.6 on 2025-06-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_collegeverificationrequest_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='l4g_group_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
