# Generated by Django 5.1.6 on 2025-06-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_institution_l4g_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.institution'),
        ),
        migrations.AlterField(
            model_name='event',
            name='program_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.program'),
        ),
    ]
