# Generated by Django 5.1.6 on 2025-06-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_completed_learner_course_progress_is_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution_Program_Requirement_General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.program')),
            ],
        ),
        migrations.CreateModel(
            name='Institution_Program_Requirement_Specific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institution')),
                ('institution_program_requirement_general_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institution_program_requirement_general')),
            ],
        ),
    ]
