# Generated by Django 5.1.6 on 2025-06-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_institution_program_requirement_general_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner_program_progress',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
